server:
  http_listen_address: 0.0.0.0
  http_listen_port: 9080

positions:
  filename: /tmp/positions.yaml

client:
  url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: system
    pipeline_stages:
      - docker:
    static_configs:
      - targets:
          - localhost
        labels:
          job: varlogs
          host: test-server
          __path__: /var/log/*.log

  - job_name: syslog
    syslog:
      listen_address: 0.0.0.0:1515
      labels:
        job: "example"
      use_incoming_timestamp: true
      label_structured_data: true
